"""
Train YOLOv8 for card detection.

Uses synthetic board images generated by board_generator.py
"""

from pathlib import Path
from ultralytics import YOLO


DATA_DIR = Path(__file__).parent.parent.parent / "data" / "synthetic"
DEFAULT_WEIGHTS_DIR = Path.home() / "data" / "set-solver" / "weights"


def train_detector(
    epochs: int = 100,
    imgsz: int = 640,
    batch: int = 16,
    model_size: str = "n",  # n=nano, s=small, m=medium
    device: str = "auto",  # auto, mps, cpu, cuda
    weights_dir: Path = None,
):
    """Train YOLOv8 on synthetic board images."""
    
    # Use default weights dir if not specified
    if weights_dir is None:
        weights_dir = DEFAULT_WEIGHTS_DIR
    weights_dir = Path(weights_dir)
    weights_dir.mkdir(parents=True, exist_ok=True)
    
    # Auto-detect best device
    if device == "auto":
        import torch
        if torch.backends.mps.is_available():
            device = "mps"
        elif torch.cuda.is_available():
            device = "cuda"
        else:
            device = "cpu"
    
    print(f"Using device: {device}")
    print(f"Saving weights to: {weights_dir}")
    
    # Load pretrained YOLOv8
    model = YOLO(f"yolo11{model_size}.pt")
    
    # Train
    results = model.train(
        data=DATA_DIR / "dataset.yaml",
        epochs=epochs,
        imgsz=imgsz,
        batch=batch,
        device=device,
        project=str(weights_dir),
        name="detector",
        exist_ok=True,
        patience=20,  # Early stopping
        save=True,
        plots=True,
    )
    
    print(f"\nTraining complete!")
    print(f"Best model: {weights_dir / 'detector' / 'weights' / 'best.pt'}")
    
    return results


def main():
    import argparse
    
    parser = argparse.ArgumentParser(description="Train card detector")
    parser.add_argument("--epochs", type=int, default=100, help="Training epochs")
    parser.add_argument("--batch", type=int, default=16, help="Batch size")
    parser.add_argument("--imgsz", type=int, default=640, help="Image size")
    parser.add_argument("--model", type=str, default="n", choices=["n", "s", "m"], 
                        help="Model size (n=nano, s=small, m=medium)")
    parser.add_argument("--device", type=str, default="auto", 
                        help="Device (auto, mps, cpu, cuda)")
    parser.add_argument("--project", type=str, default=None,
                        help=f"Weights directory (default: {DEFAULT_WEIGHTS_DIR})")
    args = parser.parse_args()
    
    train_detector(
        epochs=args.epochs,
        batch=args.batch,
        imgsz=args.imgsz,
        model_size=args.model,
        device=args.device,
        weights_dir=args.project,
    )


if __name__ == "__main__":
    main()
