"""
Train YOLOv8 for card detection.

Uses synthetic board images generated by board_generator.py
"""

from pathlib import Path
from ultralytics import YOLO


DATA_DIR = Path(__file__).parent.parent.parent / "data" / "synthetic"
WEIGHTS_DIR = Path(__file__).parent.parent.parent / "weights"


def train_detector(
    epochs: int = 100,
    imgsz: int = 640,
    batch: int = 16,
    model_size: str = "n",  # n=nano, s=small, m=medium
):
    """Train YOLOv8 on synthetic board images."""
    
    # Load pretrained YOLOv8
    model = YOLO(f"yolo11{model_size}.pt")
    
    # Train
    results = model.train(
        data=DATA_DIR / "dataset.yaml",
        epochs=epochs,
        imgsz=imgsz,
        batch=batch,
        project=str(WEIGHTS_DIR),
        name="detector",
        exist_ok=True,
        patience=20,  # Early stopping
        save=True,
        plots=True,
    )
    
    print(f"\nTraining complete!")
    print(f"Best model: {WEIGHTS_DIR / 'detector' / 'weights' / 'best.pt'}")
    
    return results


def main():
    import argparse
    
    parser = argparse.ArgumentParser(description="Train card detector")
    parser.add_argument("--epochs", type=int, default=100, help="Training epochs")
    parser.add_argument("--batch", type=int, default=16, help="Batch size")
    parser.add_argument("--imgsz", type=int, default=640, help="Image size")
    parser.add_argument("--model", type=str, default="n", choices=["n", "s", "m"], 
                        help="Model size (n=nano, s=small, m=medium)")
    args = parser.parse_args()
    
    train_detector(
        epochs=args.epochs,
        batch=args.batch,
        imgsz=args.imgsz,
        model_size=args.model,
    )


if __name__ == "__main__":
    main()
